### PR TITLE
Add fonts

### LINKED ISSUE #15: Add fonts to repo
If there anything stopping us from doing this?

Currently the `build:copyAssets` script assumes there's an `assets` directory. I'm guessing this is where the fonts are supposed to live?

### PR DESCRIPTION
**Pull request by SiAdcock**
## Why are you doing this?

Fixes #15 

Fontastique is to be the single source of truth for font storage and versioning. Therefore it needs some fonts.

These fonts were [copied from dotcom-rendering](https://github.com/guardian/dotcom-rendering/tree/master/src/static/fonts). The licence was [copied from frontend](https://github.com/guardian/frontend/blob/master/static/src/fonts/Commercial%20Type%20EULA%20Web-general.pdf). 

Formats:

- woff
- woff2
- ttf

Missing formats:

- otf

## Changes

- Add fonts

### CODE REVIEW

**Comment by paperboyo** [comment]
> Missing formats

No .otf should ever be used anywhere in digital products, so none are missing :-).

> single source of truth

💯 

Looks like everything is there, but app fonts. I leave to you how to organise those within the folder structure. They are ttf only, but different inside and have been renamed too for the ps name to always match filename (we decided NOT to do it to web fonts, even though consistency suffers).

**Comment by SiAdcock** [comment]
> No .otf should ever be used anywhere in digital products

That is good to know. I saw them in the [ios-live repo](https://github.com/guardian/ios-live/tree/master/GLA/GLA/Resources/Fonts) and assumed we'd need them here. Also @michaelbjacobson recently requested them for Apple News, maybe we can confirm whether he should be using them.

>  They are ttf only, but different inside

Wow, I didn't realise we have separate ttf fonts for apps and web. Thanks for clarifying 😄 

Let's assume this PR is just to add web fonts, and I'll create a follow-up PR adding app fonts and altering the structure.

For this PR, I'd like to establish:

- that everyone is happy for fontastique to be the source of truth for the latest fonts (web, app and maybe system fonts)
- that they should live in the `assets` directory of this repo (suggestions here welcome)
- that adding the Commercial Type licence to the repo allows us to do this

**Comment by sndrs** [comment]
> - that everyone is happy for fontastique to be the source of truth for the latest fonts (web, app and maybe system fonts)

💯

> - that they should live in the assets directory of this repo (suggestions here welcome)

i guess this depends on whether this repo is an app that contains the fonts, or a repo of the fonts with help to use them?

my gut says tucking them away in a subfolder slightly obfuscates them again. 

what if the repo looked something like:

```
/fonts
  /guardian-headline
  / etc.
/css
  /guardian-headline.css
  / etc.
/js?
README.md
  - auto-generated on release with updated URLs to all live fonts
  - guide on how to use etc?
```

so that everything this repo offers is immediately discoverable from the top level directories?

> - that adding the Commercial Type licence to the repo allows us to do this

it _must_ right? if frontend does?

**Comment by SiAdcock** [comment]
I love that structure, @sndrs, rellay good call. It's a fonts repo. Fonts should be front and centre.

@JamieB-gu can you think of a technical (Elm-related!) reason we should not do this?

I spoke to @stephanfowler about the font licence. He can't think of any additional legal stuff we need to do. Perhaps we can add the magic header when we start serving the fonts to readers, but that's further down the line.

**Comment by JamieB-gu** [comment]
`/fonts` sounds good to me 🎉

On the `css` and `js` directories, I don't know what we'd put in them 🤔. The CSS is generated by Fontastique itself, and I don't *think* we have any js?

**Comment by SiAdcock** [comment]
> The CSS is generated by Fontastique itself

Good point. I've checked in a bunch of CSS that points to the fonts, but we probably won't need this in the long run. Maybe I'll delete it for now.

In addition, Fontastique could generate CSS at build time and we can host the generated stylesheets somewhere. That way people can just include a link to our `https://assets.guim.co.uk/path/to/fonts.css` in their app and all the fonts would get downloaded. We could think about ways to make this more efficient as I doubt any application would need _all the fonts_.

**Comment by JamieB-gu** [comment]
> host the generated stylesheets somewhere
>  I doubt any application would need all the fonts

Currently you use the app to generate the CSS you need as a string. I wonder if an option to also save your custom stylesheet to `assets.guim` would be useful. For example, we could use the app to create a stylesheet tailored to the web, and another tailored to apps. Or maybe that's too complicated and we should just provide a few presets in a dropdown in Fontastique itself.

**Comment by sndrs** [comment]
> The CSS is generated by Fontastique itself

yeah i guess i'm quite not clear if this is intended as an app for generating CSS or the canonical source for fonts? 

i think they're subtly different. if this is the former, should fonts live in a @guardian/fonts package or something that maybe also contains a json map to the hashed s3 urls for current version or something? then apps that generate a scaffold to use them like fontastique use the map to generate CSS on the fly? 

there are multiple ways of consuming fonts, e.g. in frontend. 

if this is intended to be both an application to generate CSS and the canonical location for fonts, how do they get just the fonts? 

or say where/how would you create a second application that maybe auto-generated other ways of using the fonts outside of a CSS file e.g. js font-loading api?

**Comment by sndrs** [comment]
>  I doubt any application would need all the fonts

i think browsers only download fonts when they realise they need them? so the only overhead in serving extra `font-face` defs is the bytes and parse time in the CSS, which is prob not much?

**Comment by JamieB-gu** [comment]
> yeah i guess i'm quite not clear if this is intended as an app for generating CSS or the canonical source for fonts?
> if this is intended to be both an application to generate CSS and the canonical location for fonts

It is indeed intended to be both.

> how do they get just the fonts

I'm not sure I know what you mean. Are you referring to the font files themselves?

> auto-generated other ways of using the fonts outside of a CSS file e.g. js font-loading api

This is meant to handle all the different ways we consume fonts. For example, in addition to generating CSS this is also intended to generate iOS plists and Android XML files, along with zip files of the fonts to store in the app bundles (see #5). I think we can support JS font loading APIs too if needed.

>  the bytes and parse time in the CSS, which is prob not much

There are a _lot_ of fonts in this PR. Given that a `font-face` declaration is a moderate chunk of CSS, and given that I think you'd typically want them available early on (e.g. in the `<head>`) so that CSS down the page can access them, this might start to degrade performance?

> I doubt any application would need all the fonts
> i think browsers only download fonts when they realise they need them

I think it's true that this is less of an issue for browsers because, as @sndrs says, browsers only download the fonts they need. However, we're definitely going to want a very small subset for apps, given that they don't support most formats and that they need to store all the font files they use up front.

**Comment by paperboyo** [comment]
My concern is that there is not current way of the app guiding the use of no-alts, not hinted for the 99% uses. Or choosing the others for 1%.

Granted, this was always the case, but fontastique could be helpful here (by generating correct CSS dependent on needs, or by having subsets defined in CSS, even?).

**Comment by sndrs** [comment]
> I'm not sure I know what you mean. Are you referring to the font files themselves?

sorry @JamieB-gu – yes exactly. i meant if i have a need to use just the canonical font files, how do i get them into my source code? would this repo publish assets generated by the fontastique application?

**Comment by sndrs** [comment]
> There are a lot of fonts in this PR.

i think most of the variants wouldn't be available in CSS, because there's no way of testing which version your system wants from CSS. so maybe `https://assets.guim.co.uk/path/to/fonts/gaurdian-headline.css` would only include the weight and italics options, not charset and hinting

**Comment by SiAdcock** [comment]
This project started as a hack day project to try to address the issue of different apps using different versions of fonts, and as a way of leveraging the benefits of browser cached fonts. Not many people know about it and we haven't been clear, even with ourselves, on how we'll get there.

Now that we're actually adding fonts, its strategic importance is being realised. It definitely needs a doc to describe its goals and a Trello board or something to capture the roadmap. I'm keen to move these kind of questions outside of this PR though, because wherever we end up taking it, the repo will definitely need font files 😄

I'm happy to set out the goals, write an initial roadmap and open up a discussion with you all on how we proceed. Also please let me know if you have any suggestions on how we can get this kicked off properly now that it's becoming _a thing_.

**Comment by JamieB-gu** [comment]
> i meant if i have a need to use just the canonical font files, how do i get them into my source code? would this repo publish assets generated by the fontastique application?

This sounds similar to the use-case for the apps. In that model you have a button in the UI that would provide you a zip file with the following (Android example):

```
android.zip/
    font_definitions.xml
    fonts/
        GHHeadline-Bold.ttf
        GuardianTextSans-BoldIt.ttf
        ...
```

So we could provide you with copies of the font assets using this mechanism, for example.

**Comment by SiAdcock** [comment]
I've moved the fonts under `fonts/web`. I've kept the CSS and HTML that Commercial Type provided alongside the fonts. It's possibly a bit of YAGNI, but let's get a bit more clarity on the expected implementation before we get rid of it.

**Comment by sndrs** [comment]
> I'm keen to move these kind of questions outside of this PR though, because wherever we end up taking it, the repo will definitely need font files

yes sorry you're completely right :)

**Comment by SiAdcock** [comment]
I've added a [GitHub project](https://github.com/guardian/fontastique/projects/1) to track our progress. Feel free to tinker with it, I haven't set one up in ages!

**Comment by SiAdcock** [comment]
Thanks everyone for this discussion, it has been extremely helpful! 🗣

We've decided to no longer store fonts in this repo, as it appears to be doing too much. 

We've revived https://github.com/guardian/fonts (previously `frontend-fonts`). Long may it live.

This PR has been superceded by guardian/fonts#2, so I'm closing this one.

**Pull request closed without merging**
